changelog:
  categories:
    - title: ğŸš€ Features
      labels: 
        - feature
        - feat
    - title: ğŸ› Bug Fixes
      labels:
        - bug
        - fix
    - title: ğŸ”§ Maintenance
      labels:
        - chore
